name: ramadan_guide
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  uuid: ^4.5.1
  google_fonts: ^6.1.0
  flutter_localizations:
    sdk: flutter

    #  شاشة البداية
  flutter_native_splash: ^2.2.14
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/app.png
  android_gravity: center
  # في حاله الوضع المظلم
  color_dark: "#202125"
  android: true
  ios: true
  # بعد كده اعمل رن للاوامر دي
  # flutter clean
  # flutter pub get
  # flutter pub run flutter_native_splash:create


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3 # لي اضافه ايقونه للتطبيق
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app.png"
  # بعد اضافه هذا الاكواد قم بكتابه الامر ده 
  # flutter pub run flutter_launcher_icons:main
  # وسوف تجد الايقونه قد تم تغيرها
  # لو بعد كده عاوز تستبدل ايقونه قم بحذف الايقونه القديمه واضف الايقونه الجديده واعد تشغيل الامر السابق
  # وسوف تجد الايقونه قد تم تغيرها
  # واستخدم اوامر دي بعدها
  # flutter clean
  # flutter pub get
  # flutter pub run flutter_launcher_icons:main

  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/app.png
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700